name: "b hmcf\\\\"
favicon: null
layout_spectrum: 0.5902311732061207
typography_spectrum: 0.9533876124769449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6831028759479523
  lightness: 0.3787731472402811
  saturation: 0.3915718214120716
  rhythmicContrast: 0.1301488799508661
purpose: []
